### ISSUE TITLE
Como harvester, quero coletar os documentos PubMed com status Publisher e tipo Ahead of Print para complementar a busca da BVS com documentos não disponíveis em Medline

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/api-nlm#1]
- [ ] Necessidade de consultar os ID dos documentos
- [ ] Necessidade de coletar XML de cada documento
- [ ] Necessidade de coletar JSON de cada documento
- [ ] Verificar todos os status de documento disponíveis nesta coleta. A prioridade é coletar os ahead of prints

**Comment by falbrito** [comment]
Duplicado da #8.
