### ISSUE TITLE
Como harverster, quero armazenar os documentos XML no MongoDB para complementar a busca na BVS

### ISSUE THREAD

**Issue by falbrito** [bireme/api-nlm#13]
Esta user story descende da user story #2.

**Comment by renatomurasaki** [comment]
User story concluída com o desenvolvimento do [Sprint Abril 2](https://github.com/bireme/api-nlm/issues?q=milestone%3A%22Sprint+-+Abril+2%22+is%3Aclosed). O armazenamento está sendo feito no MongoDB em formato JSON
