### ISSUE TITLE
Implementar mecanismo que gera dados de log de um processo

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/api-nlm#19]
Relacionada a User Story #4.

Log de um processo
- [ ] ID (gerado a partir do sistema de armazenamento)
- [ ] Data Inicial
- [ ] Hora Inicial
- [ ] Data Final
- [ ] Hora Final
- [ ] Identificação do processo (parâmetro no script)
- [ ] Total de documentos manipulados no processo
- [ ] usuario executor do processo (user do sistema operacional)

**Comment by heitorbarbieri** [comment]
O log do processo está armazenado na coleção 'col_Log' em dois tipos de documentos:

_Documento de log do processo de download_

Documento contém os seguintes campos:
- **_id** - identificador do documento com o formato: YYYYMMDD-HH:MM:SS
- **process** - identificador do processo com o valor "aheadofprint_harvesting"
- **owner** - usuário executor do processo (definido no script 'ProcessLog.py')
- **status** - 'in process', 'broken' ou 'finished'
- **dateBegin** - data inicial do processamento. Formato: YYYYMMDD
- **hourBegin** - hora inicial do processamento. Formato: HH:MM:SS
- **dateEnd** - data final do processamento. Formato: YYYYMMDD
- **hourEnd** - hora final do processamento. Formato: HH:MM:SS
- **totAheadDocs** - número total de documentos com status "aheadofprint"
- **totNoAheadDocs** - número total de documentos com status "no_aheadofprint"
- **newAheadDocs** - número de documentos com status "aheadofprint" obtidos no último processamento
- **newNoAheadDocs** - número de documentos que mudaram de status de "aheadofprint" para "no_aheadofprint" no último processamento

_Documento de log do processo de cópia de documentos para o diretório oficial de processamento do Medline_

Documento contém os seguintes campos:
-  **_id** - identificador do documento com o formato: YYYYMMDD-HH:MM:SS
- **process** - identificador do processo com o valor "aheadofprint_moving"
- **owner** - usuário executor do processo (definido no script 'ProcessLog.py')
- **status** - 'in process', 'broken' ou 'finished'
- **dateBegin** - data inicial do processamento. Formato: YYYYMMDD
- **hourBegin** - hora inicial do processamento. Formato: HH:MM:SS
- **dateEnd** - data final do processamento. Formato: YYYYMMDD
- **hourEnd** - hora final do processamento. Formato: HH:MM:SS
- **totMovedadDocs** - número total de documentos xml movidos para o diretório de processamento
