### ISSUE TITLE
Implementar mecanismo que gera log que resume os logs de documentos de um processo

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/api-nlm#21]
Relacionado a User Story #4.

Resumo dos logs de documentos de um processo
- [ ] ID
- [ ] Data
- [ ] Hora
- [ ] Identificação do processo
- [ ] Total de documentos por estado do documento no processo
- [ ] usuario executor do processo

**Comment by heitorbarbieri** [comment]
Em conversa entre Heitor e Renato chegou-se à conclusão de que a informação "Total de documentos por estado do documento no processo" deveria estar presente no registro do log de um processo #19 e não em em log que resume os logs de documentos de um processo.
