### ISSUE TITLE
Aprimorar a comparação entre os documentos duplicados nos diretórios de dowload e processamento

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/api-nlm#23]
Ao invés de procurar os ids dentro dos documentos presentes no diretório de processamento, recuperá-los a partir de um documentos contendo um id por linha.

**Comment by heitorbarbieri** [comment]
@botturam Por favor, providenciar o documento supra citado contendo os ids. Tks.

**Comment by heitorbarbieri** [comment]
Documento de ids providenciado e mecanismo de leitura e checagem baseado no mesmo implementado.  Processo de checagem se resultado está correto foi iniciado.

**Comment by renatomurasaki** [comment]
Processo de geração da versão ISIS, a partir dos XML, está OK. Ocorreu problema no processamento destas bases ISIS e está sendo verificada por @botturam
