### ISSUE TITLE
Como harverster, quero coletar os IDs do tipo ahead of print para armazená-los em documentos no MongoDB

### ISSUE THREAD

**Issue by falbrito** [bireme/api-nlm#8]
Essa user story descende da user story #1

**Comment by falbrito** [comment]
Duplicado do #1.

**Comment by renatomurasaki** [comment]
User Story concluída no desenvolvimento do [Sprint Abril 1](https://github.com/bireme/api-nlm/issues?q=milestone%3A%22Sprint+-+Abril+1%22) .
